apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'mailhog.monitoring.svc.cluster.local:1025'
      smtp_from: 'alertmanager@example.com'
      smtp_require_tls: false

    route:
      receiver: 'email-notifications'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'hogcatcher@example.com'
        send_resolved: true
