apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: devops-tools
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "secrets", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: devops-tools
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: devops-tools
roleRef:
  kind: Role
  name: jenkins-agent-role
  apiGroup: rbac.authorization.k8s.io

