adminPassword: admin

persistence:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 10Gi

smtp:
  enabled: true
  host: mailhog.monitoring.svc.cluster.local:1025
  user: ""
  password: ""
  fromAddress: grafana@example.com
  skipVerify: true

securityContext:
  fsGroup: 472
  runAsUser: 472

initContainers:
  - name: init-chown-data
    image: busybox:1.31.1
    command:
      - sh
      - -c
      - |
        chown -R 472:472 /var/lib/grafana
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: data
        mountPath: /var/lib/grafana
