nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

server:
  retention: 10d
  persistentVolume:
    enabled: false

  extraScrapeConfigs:
    - job_name: 'kube-state-metrics'
      metrics_path: '/metrics'
      static_configs:
        - targets:
            - 'kube-state-metrics.monitoring.svc.cluster.local:8080'

alertmanager:
  configMapOverrideName: alertmanager-config
  persistentVolume:
    enabled: false

