adminUser: admin
adminPassword: changeme123

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/node-stats

dashboards:
  default:
    node-stats:
      file: /var/lib/grafana/dashboards/node-stats/node-stats.json 

persistence:
  enabled: false

extraVolumeMounts:
  - name: dashboard-config
    mountPath: /var/lib/grafana/dashboards/node-stats
    readOnly: true
  - name: alerting-config
    mountPath: /etc/grafana/provisioning/alerting
    readOnly: true

extraVolumes:
  - name: dashboard-config
    configMap:
      name: grafana-dashboard-node-stats
  - name: alerting-config
    configMap:
      name: grafana-alerting-config

