apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  high-memory-usage.yaml: |
    groups:
      - name: Memory Alerts
        interval: 30s
        rules:
          - uid: memory-usage
            title: High Memory Usage
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
                  interval: ""
                  legendFormat: "{{ instance }}"
                  refId: A
                  format: time_series
                  intervalMs: 1000
                  maxDataPoints: 43200
              - refId: C
                type: threshold
                disabled: false
                conditions:
                  - evaluator:
                      type: gt
                      params:
                        - 80
                    operator:
                      type: and
                    reducer:
                      type: avg
                    type: query
                    query:
                      refId: A
            noDataState: NoData
            execErrState: Error
            for: 5m
            annotations:
              summary: "High Memory Usage on Node"
              description: "Memory usage is above 80% for more than 5 minutes"
            labels:
              severity: critical

