persistence:
  enabled: true
  size: 5Gi
  storageClassName: "standard"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true

smtp:
  enabled: true
  host: smtp4dev.monitoring.svc.cluster.local:25
  fromAddress: grafana@example.com
  skipVerify: true

alerting:
  enabled: true
  unifiedAlerting:
    enabled: true

provisioning:
  alerting:
    enabled: true
    configMaps:
      - name: provgraf
        items:
          - cpu-alert.yaml
          - memory-alert.yaml

  contactPoints:
    enabled: true
    configMaps:
      - name: provgraf
        items:
          - contact-points.yaml

  notificationPolicies:
    enabled: true
    configMaps:
      - name: provgraf
        items:
          - notification-policies.yaml

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

