kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

alertmanager:
  enabled: true

server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  extraScrapeConfigs:
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']

    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

  retention: 15d

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 9090

