groups:
  - name: NodeAlerts
    folder: "General"
    interval: 30s
    rules:
      - uid: high-cpu
        title: High CPU usage
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance)
              format: time_series
              instant: false
              interval: ""
              intervalFactor: 2
              legendFormat: "{{instance}}"
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: "High CPU detected"
        labels:
          severity: warning

