name: Deploy Jenkins

on:
  push:
    branches:
      - task_4      
  workflow_dispatch:

env:
  KUBE_NAMESPACE: jenkins
  CHART_PATH: helm/jenkins
  RELEASE_NAME: jenkins

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.2'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Ensure namespace exists
        run: kubectl create namespace $KUBE_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Jenkins via Helm
        run: |
          helm repo add jenkins https://charts.jenkins.io || true
          helm repo update
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $KUBE_NAMESPACE \
            --values $CHART_PATH/values.yaml

